=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1109.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!-- 엘리먼트 선언 -->
<!ELEMENT booklist (kinds, book*)>
	<!ELEMENT kinds (kind*)>
		<!ELEMENT kind (#PCDATA)>
	<!ELEMENT book (title, author)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>

<!-- 속성 선언 -->
<!ATTLIST kind
		id		ID		#REQUIRED>
<!ATTLIST book
    id		ID		#REQUIRED
		kind	IDREF #REQUIRED>

=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1109.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE booklist SYSTEM "c4_1109.dtd">
<booklist>
	<!-- 책의 종류 -->
	<kinds>
		<kind id="k1">소설</kind>
		<kind id="k2">수필</kind>
		<kind id="k3">컴퓨터</kind>
	</kinds>

	<!-- 책 목록 -->
	<book id="b1" kind="k1">
		<title>시인과도둑</title>
		<author>이문열</author>
	</book>
	<book id="b2" kind="k3">
		<title>Java Programming</title>
		<author>홍길동</author>
	</book>
</booklist>
