=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1008.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!-- 루트 엘리먼트 선언 -->
<!ELEMENT booklist (book*)>
  <!ELEMENT book (title, author, publisher)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA|name)*>
			<!ELEMENT name (#PCDATA)>
	  <!ELEMENT publisher (#PCDATA)>
		<!ELEMENT image EMPTY>

=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1008.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- 문서 유형 선언 -->
<!DOCTYPE booklist SYSTEM "c4_1008.dtd">

<!-- 루트 엘리먼트 -->
<booklist>
	<book>
		<title>시인과도둑</title>
		<author>이문열</author>
		<publisher>가람기획</publisher>
	</book>
	<book>
		<title>화성에서온남자금성에서온여자</title>
		<author>
			<name>존그레이</name>
		</author>
		<publisher>친구미디어</publisher>
	</book>
</booklist>
