=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1009.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!-- 루트 엘리먼트 선언 -->
<!ELEMENT booklist (book*)>
  <!ELEMENT book (title, author, publisher)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author ANY>
	  <!ELEMENT publisher (#PCDATA)>
		<!ELEMENT image EMPTY>

<!ELEMENT name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>

=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1009.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- 문서 유형 선언 -->
<!DOCTYPE booklist SYSTEM "c4_1009.dtd">

<!-- 루트 엘리먼트 -->
<booklist>
	<book>
		<title>시인과도둑</title>
		<author>
			이문열
			<tel>016-456-7890</tel>
		</author>
		<publisher>가람기획</publisher>
	</book>
	<book>
		<title>모랫말아이들</title>
		<author>
			<name>황석영</name>
			<tel>011-123-1234</tel>
		</author>
		<publisher>친구미디어</publisher>
	</book>
</booklist>
