=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1204.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!-- 내부 파라미터 엔티티 선언 -->
<!ENTITY % maninfo "(name, age, tel)">

<!-- 엘리먼트 선언 -->
<!ELEMENT members (chief|manager|waiter)*>
	<!ELEMENT chief %maninfo;>
	<!ELEMENT manager %maninfo;>
	<!ELEMENT waiter %maninfo;>

	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT tel (#PCDATA)>

=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1204.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE members SYSTEM "c4_1204.dtd">

<members>
	<chief>
		<name>È«±æµ¿</name>
		<age>45</age>
		<tel>011-123-1234</tel>
	</chief>

	<manager>
		<name>±è¹Î¾Æ</name>
		<age>30</age>
		<tel>016-234-4567</tel>
	</manager>

	<waiter>
		<name>¹Ú¼öºó</name>
		<age>23</age>
		<tel>017-567-6789</tel>
	</waiter>
</members>
