=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1301.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!-- 노테이션 선언 -->
<!NOTATION gif PUBLIC "image/gif" "photoshop.exe">
<!NOTATION jpeg	PUBLIC "image/jpeg" "photoshop.exe">
<!NOTATION bmp PUBLIC "image/bmp" "mspaint.exe">

<!-- 엘리먼트 선언 -->
<!ELEMENT booklist (book*)>
	<!ELEMENT book (title, author, image)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT image (#PCDATA)>

<!-- 속성 선언 -->
<!ATTLIST image
		src CDATA #REQUIRED
		type NOTATION (gif|jpeg|bmp) #REQUIRED>

=== taeheungHa/haha/WebContent/xmlsource/ch4/c4_1301.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE booklist SYSTEM "c4_1301.dtd">
<booklist>
	<!-- 책 목록 -->
	<book>
		<title>시인과도둑</title>
		<author>이문열</author>
		<image src="book1.gif" type="gif"/>
	</book>
	<book>
		<title>Java Programming</title>
		<author>홍길동</author>
		<image src="book2.bmp" type="bmp"/>
	</book>
</booklist>
