=== taeheungHa/haha/WebContent/book.dtd
<?xml version="1.0" encoding="UTF-8"?>




<!ELEMENT booklist (book*)>
<!ELEMENT book (title, (author+|writer+),price,publisher,description?,image?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA|name)*>
<!ELEMENT writer (#PCDATA|name)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image EMPTY>
<!ELEMENT qty ANY>

<!ATTLIST book kind (컴퓨터|소설|수필) "컴퓨터" id ID #REQUIRED>
<!ATTLIST nation CDATA>
<!ELEMENT kr "대한민국">
<!ELEMENT fr "프랑스">
<!ELEMENT usa "미국">
<!ATTLIST author nation CDATA>
<!ATTLIST writer nation CDATA>

=== taeheungHa/haha/WebContent/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "book.dtd">

<booklist>
<book kind ="컴퓨터" id="C001">
<title>자바</title>
<author nation="&kr;">이자바</author>
<author>
<name>홍자바</name>
<nation>&usa;</nation> 
</author>
<price>2000</price>
<publisher>한빛</publisher>
<description>참 쉽죠</description>
<image/>
<qty>100
<price>20000</price>
</qty>
</book>


</booklist>
