=== taeheungHa/haha/WebContent/xmlsource/ch6/c6_1202.xsd
<?xml version="1.0" encoding="euc-kr"?>
<xsd:schema	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
	<!-- 루트 엘리먼트 선언 -->  
  <xsd:element name="booklist" type="ctBooklist"/>
  
	<!-- 글로벌 컴플렉스 타입 정의 -->
	<xsd:complexType name="ctBooklist">
		<xsd:sequence>
			<xsd:element name="book" type="ctBook" maxOccurs="unbounded"/>
		</xsd:sequence>		
	</xsd:complexType>

	<xsd:complexType name="ctBook">
		<xsd:sequence>
			<xsd:element name="title" type="xsd:string"/>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="author" type="xsd:string"/>
				<xsd:element name="writer" type="xsd:string"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== taeheungHa/haha/WebContent/xmlsource/ch6/c6_1202.xml
<?xml version="1.0" encoding="euc-kr"?>
<booklist  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		       xsi:noNamespaceSchemaLocation="c6_1202.xsd">

	<book>
		<title>XML Programming</title>
		<author>╫е╧нц╤</author>
	</book>

	<book>
		<title>DB Programming</title>
		<writer>ц╓╠теб</writer>
	</book>

	<book>
		<title>JDBC Programming</title>
		<author>╫е╧нц╤</author>
		<author>ц╓╠теб</author>
	</book>

</booklist>
