=== taeheungHa/haha/WebContent/xmlsource/ch6/c6_1501.xsd
<?xml version="1.0" encoding="euc-kr"?>
<xsd:schema	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
	<!-- 루트 엘리먼트 선언 -->  
  <xsd:element name="booklist" type="ctBooklist"/>

	<!-- 글로벌 컴플렉스 타입 정의 -->
	<xsd:complexType name="ctBooklist">
		<xsd:sequence>
			<xsd:element name="kinds" type="ctKinds"/>
			<xsd:element name="book" type="ct1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ctKinds">
		<xsd:sequence>
			<xsd:element name="kind" type="ct1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ct1">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="id" type="xsd:ID" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>		
	</xsd:complexType>

</xsd:schema>

=== taeheungHa/haha/WebContent/xmlsource/ch6/c6_1501.xml
<?xml version="1.0" encoding="euc-kr"?>
<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:noNamespaceSchemaLocation="c6_1501.xsd">

	<kinds>
		<kind id="k1">컴퓨터</kind>
		<kind id="k2">소설</kind>
		<kind id="k3">잡지</kind>
	</kinds>

	<book id="b1">XML 기초서</book>
	<book id="b2">.NET And XML</book>
	<book id="b3">Java And XML</book>

</booklist>
